name: Setup Python with uv and install project
description: Create venv with uv and install the project.
inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    # NOTE: you may be tempted to add some caching like then below, but this actually
    # leads to similar overall installation because of the time required to download the
    # large cached uv environment. Prefer to remove it then for simplicity.
    # - name: Cache uv dependencies
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cache/uv
    #       .venv
    #     key: uv-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml', '**/prpl_requirements.txt') }}
    #     restore-keys: |
    #       uv-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv venv --python=${{ inputs.python-version }}
    - name: Install the project
      shell: bash
      run: uv run python scripts/install_all.py
