"""Constants for KinDER models."""

# Base and arm RPC servers
BASE_RPC_HOST = "localhost"
BASE_RPC_PORT = 50000
ARM_RPC_HOST = "localhost"
ARM_RPC_PORT = 50001
RPC_AUTHKEY = b"secret password"

# Policy
POLICY_SERVER_HOST = "localhost"
POLICY_SERVER_PORT = 5555
POLICY_CONTROL_FREQ = 100
POLICY_CONTROL_PERIOD = 1.0 / POLICY_CONTROL_FREQ
POLICY_IMAGE_WIDTH = 224
POLICY_IMAGE_HEIGHT = 224

POLICY_IMAGE_WIDTH_VLA = 224
POLICY_IMAGE_HEIGHT_VLA = 224
