import numpy as np

# Base and arm RPC servers
BASE_RPC_HOST = "localhost"
BASE_RPC_PORT = 50000
ARM_RPC_HOST = "localhost"
ARM_RPC_PORT = 50001
RPC_AUTHKEY = b"secret password"

# Policy
POLICY_SERVER_HOST = "localhost"
POLICY_SERVER_PORT = 5555
POLICY_CONTROL_FREQ = 10
POLICY_CONTROL_PERIOD = 1.0 / POLICY_CONTROL_FREQ
POLICY_IMAGE_WIDTH = 84
POLICY_IMAGE_HEIGHT = 84
