[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "prpl_tidybot"
version = "0.1.0"
description = "Code for interfacing with the real TidyBot++ robot."
readme = "README.md"
requires-python = ">=3.10.14, <3.13"
dependencies = [
   "numpy",
   "threadpoolctl>=3.5.0",
   "scipy>=1.12.0", 
   "opencv-python>=4.9.0.80", 
   "h5py",
   "mujoco==3.2.4",
   "tqdm", 
   "notebook",
   "matplotlib",
   "pin==2.7.0",
   "ruckig==0.12.2",
   "flask==3.0.2",
   "flask_socketio==5.3.6",
   "pyzmq==25.1.2",
   "redis==5.0.6",
   "phoenix6",
   "pygame==2.5.2",
   "spatialmath-python",
   "kortex-api",
]

[project.optional-dependencies]
develop = [
    "black",
    "docformatter",
    "isort",
    "mypy",
    "pylint>=2.14.5",
    "pytest-pylint>=0.18.0",
    "pytest>=7.2.2",
]

[tool.uv]
override-dependencies = ["protobuf==3.20.0"]

[tool.uv.sources]
kortex-api = {path = "kortex_wheels/kortex_api-2.6.0.post3-py3-none-any.whl"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
prpl_tidybot = ["py.typed"]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
py_version = 310
profile = "black"
multi_line_output = 2
skip_glob = ["venv/*", ".venv/*"]
split_on_trailing_comma = true

[tool.docformatter]
line-length = 88
wrap-summaries = 88
wrap-descriptions = 88

[tool.mypy]
strict_equality = true
disallow_untyped_calls = true
warn_unreachable = true
exclude = ["venv/*", ".venv/*"]

[[tool.mypy.overrides]]
module = [
    "spatialmath.*",
]
ignore_missing_imports = true
