name: CI Checks

on: [push]

jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run autoformat
        run: uv run ./run_in_all_packages.sh "./run_autoformat.sh"

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: |
          uv run ./run_in_all_packages.sh "pytest . --pylint -m pylint --pylint-rcfile=.pylintrc"

  static-type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Mypy
        run: |
          uv run ./run_in_all_packages.sh "mypy ."

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install LAPACK, BLAS, OSMesa (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev libosmesa6-dev libgl1 libglx-mesa0
      - name: Install GLFW (Macos)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install glfw
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        shell: bash
        run: uv venv --python=3.10
      - name: Install the project
        shell: bash
        run: uv run ./install_all.sh
      - name: Pytest
        run: |
          uv run ./run_in_all_packages.sh "pytest tests/"

  unit-tests-pybullet-helpers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Install LAPACK and BLAS
      run: |
        sudo apt-get update
        sudo apt-get install -y liblapack-dev libblas-dev
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}    
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Pytest
      run: |
       uv run pytest tests/